pipeline {
    // agent {
    //     docker {
    //         image 'node:lts-buster-slim'
    //         args '-p 3000:3000'
    //     }
    // }
    agent any

    stages {
        stage('build'){
            steps {
                sh nodejs(nodeJSInstallationName: 'Node 6.x', configId: '<config-file-provider-id>') {
                    sh 'npm config ls'
            }
        }
        stage('test'){
            steps{
                echo 'testing the application'
            }
        }
        stage('deploy'){
            steps{
                echo 'deploying the application'
            }
        }
    }
}

// docker run -d --rm --name=agent1 -p 22:22 \
// -e "JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCzwj6fufIeDpmIlHSVVJidPBPElhjaib4XkFvjUtCqv5Qm5nAOVwfJESK54MVPmr4ctHTzEJD9TPLwom/ZOLq2ENvFI2ZWAUEBw2FMdJYmGKpgiO/DbBQKJB7TS1lp7WyyFFIFZKxy2K/PZXTC7xuc5P/Offkut2tF5AqTjytc7P+S7tCvOxoPpk0YRo3JNFoXzM/acwGrkLTGojt+seqpzbzpUZ3jAwR6Wao9ORFpYpPRvNv2d+604+1H1VNfrJaUlGHgCge8XgTRugQfmIGYXQX5F/J/AwLozVzdgyyxYCNOGaFR63vg32dakQxURotlDbrzXOfPpCcnc7gXAJFOhmpTdbqlFEdkWVuQdOolv8Dq7BPdovbkHbKNUOPLC/Dsu/564WH9a71+wDxU2gbB4P3+dMaPJqwy3p9ZfhqrUmBUc4eTn6MA6PhAc1QJyJZDbFk5iYxL21pgXQfbr9WBqEAr7WSyE3uQFbqwHM8NE5H18esgRfF8LrMpy+Z5tQE" \
// jenkins/ssh-agent:alpine

// cat ~/.ssh/jenkins_agent_key.pub >> ~/.ssh/authorized_keys
// cat $home/jenkins/jenkinskey.pub