pipeline {
    agent any 

    stages {
        stage('build'){
            steps {
                sh 'docker stack deploy -c melilabs.yml melilabs'
            }
        }
        stage('test'){
            steps{
                echo 'testing the application'
            }
        }
        stage('deploy'){
            steps{
                echo 'deploying the application'
            }
        }
    }
}