pipeline {

    stages {
        stage('build'){
            steps {
                sh './start.sh'
            }
        }
        stage('test'){
            steps{
                echo 'testing the application'
            }
        }
        stage('deploy'){
            steps{
                echo 'deploying the application'
            }
        }
    }
}